---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart) %>%
  filter(order_dow == 0, reordered == 1) %>%
  drop_na()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart A: The count of orders in different aisles (only including aisles with a count of orderd greater than 5000 ) 


```{r}
instacart %>%
  count(aisle) %>%
  filter(n > 5000) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  mutate(count = n) %>%
  plot_ly(x = ~aisle, y = ~count, type = "bar", color = ~aisle, alpha = 0.5, colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: The hour of the day on which the order was placed among different aisles in department of alcohol


```{r}
instacart %>%
  filter(department == "alcohol") %>%
  mutate(order_hour = order_hour_of_day) %>%
  plot_ly(x = ~aisle, y = ~order_hour, type = "scatter", mode = "markers",
          alpha = .5)
```


### Chart C: The hour of the day on which the order was placed among selected departments


```{r}
instacart %>%
  mutate(department = fct_reorder(department, order_hour_of_day),
         order_hour = order_hour_of_day) %>% 
  filter(department %in% c("bakery", "canned goods", "meat seafood", "alcohol",
                           "beverages","diary eggs","deli","frozen", "snacks")) %>%
  plot_ly(
    y = ~ order_hour, color = ~department, type = "violin",
    colors = "viridis")
```

